/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Grafo.Adyacencia;
import Controlador.Grafo.Grafo;
import Controlador.Grafo.GrafoNoDirigidoEtiquetado;
import Controlador.ListaEnlazada.ListaEnlazada;
import Controlador.PosicionController;
import Modelo.Locales;
import static Vista.frmAgregarLocal.listaLocales;
import static Vista.frmAgregarLocal.txtDistanciaAgregar;
import static Vista.frmAgregarLocal.txtNombreAgregar;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import vista.frmPresentacionGrafos;


/**
 *
 * @author Victor
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    DefaultTableModel modeloTabla = new DefaultTableModel();

    private static JFrame frmModificarLocal;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        modeloTabla.addColumn("id");
        modeloTabla.addColumn("Nombre Local");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Distancia");
        
        modeloTabla.setColumnIdentifiers(new Object[]{"id","Nombre Local", "Descripcion", "Distancia"});
        
        CargarLocales();
    }
    
    
    
    public boolean ExisteEnTabla(JTable tabla, String dto, int col) {

        boolean Existe = false;

        for (int i = 0; i < tabla.getRowCount(); i++) {

            if (tabla.getValueAt(i, col).equals(dto)) {
//                tabla.setValueAt(nuevoValor, i, 1);
//                tabla.setValueAt(FechaActualizada, i, 3);

                Existe = true;
            }
        }
        return Existe;
    }
    
    public void CargarLocales() {
        
        try {
            Gson gson = new Gson();
            FileReader reader;
            reader = new FileReader("ListaLocales.json");
            
            LinkedList<Locales> ListaLocalesGuardados = gson.fromJson(reader, new TypeToken<LinkedList<Locales>>() {}.getType());

            for (Locales locales : ListaLocalesGuardados) {
                if (!ExisteEnTabla(tblListaLocales, locales.getId().toString(), 0)) {
                    modeloTabla.addRow(new Object[]{locales.getId(), locales.getNombreLocal(), locales.getDescripcion(), locales.getDistancia()});
                    tblListaLocales.setModel(modeloTabla);
                } 
                else {

                }
            }
        } 
        catch (FileNotFoundException e) {

        }
    }
    
    public void EliminarDato(){
        
        int filaselecionada = tblListaLocales.getSelectedRow();
        if (filaselecionada >= 0) {
            modeloTabla.removeRow(filaselecionada);
            
            try {
                
                Gson gson = new Gson();
                FileReader reader;
                reader = new FileReader("ListaLocales.json");

                LinkedList<Locales> ListaLocalesGuardados = gson.fromJson(reader, new TypeToken<LinkedList<Locales>>() {}.getType());

//                System.out.println(""+filaselecionada);
                
                ListaLocalesGuardados.remove(filaselecionada);
                
                try {
                    FileWriter writer;
                    writer = new FileWriter("ListaLocales.json");
                    gson.toJson(ListaLocalesGuardados, writer);
                    writer.close();
                } 
                catch (IOException ex) {
                    Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } 
            catch (FileNotFoundException ex) {
                Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        else {
            JOptionPane.showMessageDialog(null, "Seleccione el medicamento a eliminar", "Seleccione una fila", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreLocal = new javax.swing.JTextField();
        txtDescripcionLocal = new javax.swing.JTextField();
        txtPosicion = new javax.swing.JTextField();
        btnCrearLocal = new javax.swing.JButton();
        btnEditarLocal = new javax.swing.JButton();
        btnEliminarLocal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaLocales = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnRecorridoDijstra = new javax.swing.JButton();
        btnRecorridoFloyd = new javax.swing.JButton();
        btnMostrarGrafos = new javax.swing.JButton();
        btnBotonBusquedaAnchura = new javax.swing.JButton();
        btnBusquedaEnProfundidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOCALES");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMACION DE LOCALES");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Posicion:");

        txtNombreLocal.setEditable(false);
        txtNombreLocal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreLocal.setFocusable(false);

        txtDescripcionLocal.setEditable(false);
        txtDescripcionLocal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescripcionLocal.setFocusable(false);

        txtPosicion.setEditable(false);
        txtPosicion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPosicion.setFocusable(false);

        btnCrearLocal.setText("CREAR LOCAL");
        btnCrearLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLocalActionPerformed(evt);
            }
        });

        btnEditarLocal.setText("EDITAR LOCAL");
        btnEditarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLocalActionPerformed(evt);
            }
        });

        btnEliminarLocal.setText("ELIMINAR LOCAL");
        btnEliminarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPosicion)
                                    .addComponent(txtDescripcionLocal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreLocal, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarLocal)
                        .addGap(0, 3, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcionLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearLocal)
                    .addComponent(btnEditarLocal)
                    .addComponent(btnEliminarLocal))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LISTADO DE LOCALES");

        tblListaLocales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListaLocales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaLocalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaLocales);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRecorridoDijstra.setText("RECORRIDO DIJKSTRA");

        btnRecorridoFloyd.setText("RECORRIDO FLOYD");
        btnRecorridoFloyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoFloydActionPerformed(evt);
            }
        });

        btnMostrarGrafos.setText("MOSTRAR GRAFOS");
        btnMostrarGrafos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarGrafosActionPerformed(evt);
            }
        });

        btnBotonBusquedaAnchura.setText("BPA");

        btnBusquedaEnProfundidad.setText("BPP");
        btnBusquedaEnProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaEnProfundidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMostrarGrafos))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBusquedaEnProfundidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBotonBusquedaAnchura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecorridoFloyd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecorridoDijstra))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRecorridoDijstra)
                    .addComponent(btnRecorridoFloyd)
                    .addComponent(btnMostrarGrafos)
                    .addComponent(btnBotonBusquedaAnchura)
                    .addComponent(btnBusquedaEnProfundidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLocalActionPerformed
        // TODO add your handling code here:
        frmAgregarLocal abrir = new frmAgregarLocal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearLocalActionPerformed

    private void btnEditarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLocalActionPerformed
        
        
        if(tblListaLocales.getSelectedRowCount() != 1){
            JOptionPane.showMessageDialog(null, "Seleccione un local para editar", "NO SELECCIONADO", JOptionPane.WARNING_MESSAGE);

        }
        else{
            
            if (frmModificarLocal == null) {
                frmModificarLocal = new frmModificarLocal();
                frmModificarLocal.setVisible(true);
                this.setVisible(false);
            } 
            else {
                frmModificarLocal.dispose();
                frmModificarLocal = null;
//                frmModificarLocal.toFront();
            }
        }
        

    }//GEN-LAST:event_btnEditarLocalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblListaLocalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaLocalesMouseClicked
        // TODO add your handling code here:
        int seleccionar = tblListaLocales.rowAtPoint(evt.getPoint());
        
        txtNombreLocal.setText( tblListaLocales.getValueAt(seleccionar, 1).toString());
        txtDescripcionLocal.setText( tblListaLocales.getValueAt(seleccionar, 2).toString());
        txtPosicion.setText(tblListaLocales.getValueAt(seleccionar, 3).toString());
        
        
    }//GEN-LAST:event_tblListaLocalesMouseClicked

    private void btnMostrarGrafosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarGrafosActionPerformed
        // TODO add your handling code here:
        
        try {
            Gson gson = new Gson();
            FileReader reader = new FileReader("ListaLocales.json");
            
            LinkedList<Locales> ListaLocalesGuardados = gson.fromJson(reader, new TypeToken<LinkedList<Locales>>() {}.getType());

//            for (Locales local : ListaLocalesGuardados) {
//                System.out.println(local.getNombreLocal() + " " + local.getDescripcion());
//            }
            GrafoNoDirigidoEtiquetado grafoDirigiodoEtiquetado = new GrafoNoDirigidoEtiquetado(ListaLocalesGuardados.size(), String.class);
            
            for (int i = 0; i < ListaLocalesGuardados.size();i++) {
//                System.out.println(""+i);
                Locales listaLocalGuardada = ListaLocalesGuardados.get(i);
//                System.out.println(""+i);
//                System.out.println(""+local);
                grafoDirigiodoEtiquetado.etiquetarVertice(i+1, listaLocalGuardada.getNombreLocal());
            }
            
            for (int i = 0; i < ListaLocalesGuardados.size() - 1; i++) {
                Locales local1 = ListaLocalesGuardados.get(i);
                for (int j = i + 1; j < ListaLocalesGuardados.size(); j++) {
                    Locales local2 = ListaLocalesGuardados.get(j);
                    try {
//                        if (!grafoDirigiodoEtiquetado.existeArista(i,i)) {
//                            if (!grafoDirigiodoEtiquetado.existeArista(j,j)) {
                            grafoDirigiodoEtiquetado.insertarAristaE(local1.getNombreLocal(), local2.getNombreLocal(), Double.parseDouble(local1.getDistancia()));
//                        }}
//                        grafoDirigiodoEtiquetado.insertarAristaE(local1.getNombreLocal(), local2.getNombreLocal(), Double.parseDouble(local1.getDistancia()));
                    } 
                    catch (Exception e) {
                        
                    }
                    
                }
            }
            
//            for (int i = 0; i < ListaLocalesGuardados.size(); i++) {
//                Locales local1 = ListaLocalesGuardados.get(i);
//
//                try {
//                    grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(1), grafoDirigiodoEtiquetado.obtenerEtiqueta(2), Double.parseDouble(local1.getDistancia()));
//                    grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(2), grafoDirigiodoEtiquetado.obtenerEtiqueta(3), Double.parseDouble(local1.getDistancia()));
//                    grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(3), grafoDirigiodoEtiquetado.obtenerEtiqueta(4), Double.parseDouble(local1.getDistancia()));
//                } 
//                catch (Exception e) {
//
//                }
//            }
//            for (Locales local : ListaLocalesGuardados) {
//                for (int i = 0; i < ListaLocalesGuardados.size(); i++) {
//                    
//                    Locales locales = ListaLocalesGuardados.get(i);
//
//                    grafoDirigiodoEtiquetado.etiquetarVertice(i, local.getNombreLocal());                    
//                    
//                    try {
//                        grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(1), grafoDirigiodoEtiquetado.obtenerEtiqueta(1), Double.parseDouble(locales.getDistancia()));
//                        
//                    } 
//                    catch (Exception e) {
//
//                    }
//                    
//                }
//            }
            new frmPresentacionGrafos(null, true, grafoDirigiodoEtiquetado, 1).setVisible(true);
            
//            for (int i = 0; i < ListaLocalesGuardados.size(); i++) {
//                
//                GrafoNoDirigidoEtiquetado grafoDirigiodoEtiquetado = new GrafoNoDirigidoEtiquetado(i, String.class);
//                Locales locales = ListaLocalesGuardados.get(i);
//                
//                for (Locales local : ListaLocalesGuardados) {
////                    for(int j = i; j < ListaLocalesGuardados.size(); j++){
//                        grafoDirigiodoEtiquetado.etiquetarVertice(1, local.getNombreLocal());
////                    }
//                }
//
//                try {
//                    grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(1), grafoDirigiodoEtiquetado.obtenerEtiqueta(1), Double.parseDouble(locales.getDistancia()));
//
//                    
//                } 
//                catch (Exception e) {
//
//                }
//                new frmPresentacionGrafos(null, true, grafoDirigiodoEtiquetado, 1).setVisible(true);
//            }
        } 
        catch (FileNotFoundException e) {

        }


        
//        GrafoNoDirigidoEtiquetado grafoDirigiodoEtiquetado = new GrafoNoDirigidoEtiquetado(7, String.class);

//        grafoDirigiodoEtiquetado.etiquetarVertice(1, "1");
//        grafoDirigiodoEtiquetado.etiquetarVertice(2, "2");
//        grafoDirigiodoEtiquetado.etiquetarVertice(3, "3");
//        grafoDirigiodoEtiquetado.etiquetarVertice(4, "4");
//        grafoDirigiodoEtiquetado.etiquetarVertice(5, "5");
//        grafoDirigiodoEtiquetado.etiquetarVertice(6, "6");
//        grafoDirigiodoEtiquetado.etiquetarVertice(7, "7");
       
//        try {
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(1), grafoDirigiodoEtiquetado.obtenerEtiqueta(2), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(2), grafoDirigiodoEtiquetado.obtenerEtiqueta(3), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(3), grafoDirigiodoEtiquetado.obtenerEtiqueta(4), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(4), grafoDirigiodoEtiquetado.obtenerEtiqueta(5), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(5), grafoDirigiodoEtiquetado.obtenerEtiqueta(6), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(6), grafoDirigiodoEtiquetado.obtenerEtiqueta(7), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(7), grafoDirigiodoEtiquetado.obtenerEtiqueta(1), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(3), grafoDirigiodoEtiquetado.obtenerEtiqueta(6), 30.0);
//            grafoDirigiodoEtiquetado.insertarAristaE(grafoDirigiodoEtiquetado.obtenerEtiqueta(6), grafoDirigiodoEtiquetado.obtenerEtiqueta(3), 30.0);
//            
//            int Inicio = Integer.parseInt(JOptionPane.showInputDialog("mete el origen"));
//            int fin = Integer.parseInt(JOptionPane.showInputDialog("mete el fin"));
            
//            grafoDirigiodoEtiquetado.caminoMinimo(Inicio, fin).imprimir();
//            grafoDirigiodoEtiquetado.caminoMinimo(3, 7).imprimir();
//
//            new FrmGrafo(null, true, grafoDirigiodoEtiquetado, 1).setVisible(true); 
//       } 
//        catch (Exception e) {
//            
//        }
    }//GEN-LAST:event_btnMostrarGrafosActionPerformed

    private void btnEliminarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLocalActionPerformed
        // TODO add your handling code here:
        EliminarDato();
    }//GEN-LAST:event_btnEliminarLocalActionPerformed

    private void btnRecorridoFloydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoFloydActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRecorridoFloydActionPerformed

    private void btnBusquedaEnProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaEnProfundidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBusquedaEnProfundidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotonBusquedaAnchura;
    private javax.swing.JButton btnBusquedaEnProfundidad;
    private javax.swing.JButton btnCrearLocal;
    private javax.swing.JButton btnEditarLocal;
    private javax.swing.JButton btnEliminarLocal;
    private javax.swing.JButton btnMostrarGrafos;
    private javax.swing.JButton btnRecorridoDijstra;
    private javax.swing.JButton btnRecorridoFloyd;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblListaLocales;
    public static javax.swing.JTextField txtDescripcionLocal;
    public static javax.swing.JTextField txtNombreLocal;
    public static javax.swing.JTextField txtPosicion;
    // End of variables declaration//GEN-END:variables
}
